site_name: pytest-fold
site_description: A Pytest plugin to make console output more manageable
site_author: Jeff Wright

theme: readthedocs

repo_url: https://github.com/jeffwright13/pytest-fold

pages:
- Home: index.md
